project_id = "kpuqqqaqiwxbjpbmmcfz"

[functions.payment-callback]
verify_jwt = false

[functions.create-payment]
verify_jwt = true

[functions.optimize-image]
verify_jwt = false

[functions.tawk-to-telegram]
verify_jwt = false

[functions.telegram-webhook]
verify_jwt = false
