import { AlertCircle, CheckCircle, Download, Sparkles } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { ParsedProduct } from './types';
import { exportFailedRows } from './templates';
import { useLanguage } from '@/contexts/LanguageContext';
import { ScrollArea } from '@/components/ui/scroll-area';

interface ValidationStepProps {
  products: ParsedProduct[];
  onValidate: () => void;
  isValidating: boolean;
}

export function ValidationStep({ products, onValidate, isValidating }: ValidationStepProps) {
  const { lang } = useLanguage();

  const validProducts = products.filter(p => p.errors.length === 0);
  const invalidProducts = products.filter(p => p.errors.length > 0);

  const translations = {
    en: {
      title: 'Validation Results',
      total: 'Total Rows',
      valid: 'Valid',
      invalid: 'Invalid',
      exportFailed: 'Export Failed Rows',
      errorDetails: 'Error Details',
      row: 'Row',
      field: 'Field',
      value: 'Value',
      error: 'Error',
      validating: 'Validating...',
      validate: 'Validate Data',
      noErrors: 'All rows are valid! You can proceed with import.',
      hasErrors: 'Some rows have validation errors. Fix them or export and correct the CSV.',
      seoPreview: 'SEO Fields Preview',
      seoInfo: 'SEO fields (meta_title and meta_description) have been automatically generated for products where they were not provided in the CSV.',
      autoGenerated: 'Auto-generated',
      showingSample: 'Showing first 3 valid products with auto-generated SEO:',
      product: 'Product',
    },
    ru: {
      title: 'Результаты валидации',
      total: 'Всего строк',
      valid: 'Валидных',
      invalid: 'Невалидных',
      exportFailed: 'Экспортировать ошибки',
      errorDetails: 'Детали ошибок',
      row: 'Строка',
      field: 'Поле',
      value: 'Значение',
      error: 'Ошибка',
      validating: 'Валидация...',
      validate: 'Проверить данные',
      noErrors: 'Все строки валидны! Можете продолжить импорт.',
      hasErrors: 'Некоторые строки содержат ошибки. Исправьте их или экспортируйте и поправьте CSV.',
      seoPreview: 'Предпросмотр SEO полей',
      seoInfo: 'SEO поля (meta_title и meta_description) были автоматически сгенерированы для товаров, где они не были указаны в CSV.',
      autoGenerated: 'Авто-генерация',
      showingSample: 'Показаны первые 3 валидных товара с авто-генерацией SEO:',
      product: 'Товар',
    },
  };

  const t = translations[lang];

  if (products.length === 0) {
    return (
      <div className="text-center py-8">
        <Button onClick={onValidate} disabled={isValidating}>
          {isValidating ? t.validating : t.validate}
        </Button>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div>
        <h3 className="text-lg font-semibold mb-4">{t.title}</h3>
        
        <div className="grid grid-cols-3 gap-4 mb-6">
          <div className="bg-gray-100 dark:bg-gray-800 rounded-lg p-4">
            <p className="text-sm text-gray-600 dark:text-gray-400">{t.total}</p>
            <p className="text-2xl font-bold">{products.length}</p>
          </div>
          <div className="bg-green-100 dark:bg-green-900 rounded-lg p-4">
            <p className="text-sm text-green-700 dark:text-green-300">{t.valid}</p>
            <p className="text-2xl font-bold text-green-700 dark:text-green-300">
              {validProducts.length}
            </p>
          </div>
          <div className="bg-red-100 dark:bg-red-900 rounded-lg p-4">
            <p className="text-sm text-red-700 dark:text-red-300">{t.invalid}</p>
            <p className="text-2xl font-bold text-red-700 dark:text-red-300">
              {invalidProducts.length}
            </p>
          </div>
        </div>

        {invalidProducts.length === 0 ? (
          <>
            <div className="bg-green-50 dark:bg-green-950 border border-green-200 dark:border-green-800 rounded-lg p-4 flex items-start gap-3">
              <CheckCircle className="h-5 w-5 text-green-600 dark:text-green-400 mt-0.5" />
              <p className="text-sm text-green-800 dark:text-green-200">{t.noErrors}</p>
            </div>

            {/* SEO Preview Section */}
            {validProducts.some(p => 
              p.seoAutoGenerated?.meta_title || 
              p.seoAutoGenerated?.meta_description
            ) && (
              <div className="mt-6">
                <div className="flex items-center gap-2 mb-3">
                  <Sparkles className="h-5 w-5 text-blue-600 dark:text-blue-400" />
                  <h4 className="font-semibold">{t.seoPreview}</h4>
                </div>
                
                <div className="bg-blue-50 dark:bg-blue-950 border border-blue-200 dark:border-blue-800 rounded-lg p-4 mb-4">
                  <p className="text-sm text-blue-800 dark:text-blue-200">{t.seoInfo}</p>
                </div>

                <p className="text-sm text-gray-600 dark:text-gray-400 mb-3">{t.showingSample}</p>
                
                <div className="space-y-3">
                  {validProducts
                    .filter(p => 
                      p.seoAutoGenerated?.meta_title || 
                      p.seoAutoGenerated?.meta_description
                    )
                    .slice(0, 3)
                    .map((product, idx) => (
                      <div key={idx} className="border rounded-lg p-4 bg-white dark:bg-gray-800">
                        <div className="flex items-start justify-between mb-2">
                          <div className="flex-1">
                            <p className="font-medium text-sm mb-1">
                              {t.product}: {product.data.name_en || product.data.name_ru}
                            </p>
                            <Badge variant="secondary" className="text-xs">
                              {t.row} {product.row}
                            </Badge>
                          </div>
                        </div>
                        
                        <div className="space-y-2 mt-3">
                          <div>
                            <div className="flex items-center gap-2 mb-1">
                              <span className="text-xs font-medium text-gray-600 dark:text-gray-400">
                                Meta Title:
                              </span>
                              {product.seoAutoGenerated?.meta_title && (
                                <Badge variant="outline" className="text-xs">
                                  <Sparkles className="h-3 w-3 mr-1" />
                                  {t.autoGenerated}
                                </Badge>
                              )}
                            </div>
                            <p className="text-sm bg-gray-50 dark:bg-gray-900 p-2 rounded">
                              {product.data.meta_title || '—'}
                            </p>
                          </div>
                          
                          <div>
                            <div className="flex items-center gap-2 mb-1">
                              <span className="text-xs font-medium text-gray-600 dark:text-gray-400">
                                Meta Description:
                              </span>
                              {product.seoAutoGenerated?.meta_description && (
                                <Badge variant="outline" className="text-xs">
                                  <Sparkles className="h-3 w-3 mr-1" />
                                  {t.autoGenerated}
                                </Badge>
                              )}
                            </div>
                            <p className="text-sm bg-gray-50 dark:bg-gray-900 p-2 rounded">
                              {product.data.meta_description || '—'}
                            </p>
                          </div>
                        </div>
                      </div>
                    ))}
                </div>
              </div>
            )}
          </>
        ) : (
          <>
            <div className="bg-red-50 dark:bg-red-950 border border-red-200 dark:border-red-800 rounded-lg p-4 flex items-start gap-3 mb-4">
              <AlertCircle className="h-5 w-5 text-red-600 dark:text-red-400 mt-0.5" />
              <p className="text-sm text-red-800 dark:text-red-200">{t.hasErrors}</p>
            </div>

            <div className="flex justify-end mb-4">
              <Button
                variant="outline"
                size="sm"
                onClick={() => exportFailedRows(invalidProducts as unknown as { row: number; data: Record<string, unknown>; errors: { field: string; message: string }[] }[], lang)}
              >
                <Download className="mr-2 h-4 w-4" />
                {t.exportFailed}
              </Button>
            </div>

            <div className="border rounded-lg">
              <div className="bg-gray-100 dark:bg-gray-800 px-4 py-2 font-semibold text-sm border-b">
                {t.errorDetails}
              </div>
              <ScrollArea className="h-[400px]">
                <div className="divide-y">
                  {invalidProducts.map((product, idx) => (
                    <div key={idx} className="p-4 space-y-2">
                      <div className="flex items-center gap-2 mb-2">
                        <Badge variant="destructive">
                          {t.row} {product.row}
                        </Badge>
                        <span className="text-sm text-gray-600 dark:text-gray-400">
                          {product.data.name_en || 'Unnamed product'}
                        </span>
                      </div>
                      <div className="space-y-1">
                        {product.errors.map((error, errorIdx) => (
                          <div
                            key={errorIdx}
                            className="text-xs bg-red-50 dark:bg-red-950 p-2 rounded"
                          >
                            <span className="font-medium">{error.field}:</span>{' '}
                            <span className="text-red-700 dark:text-red-300">
                              {error.message}
                            </span>
                            {error.value && (
                              <span className="text-gray-600 dark:text-gray-400">
                                {' '}(value: {String(error.value)})
                              </span>
                            )}
                          </div>
                        ))}
                      </div>
                    </div>
                  ))}
                </div>
              </ScrollArea>
            </div>
          </>
        )}
      </div>
    </div>
  );
}
